/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*
CREATE DATABASE projcadastros 
;
USE projcadastros;
DROP TABLE IF EXISTS objeto;
CREATE TABLE objeto (
  IDProduto int(11) NOT NULL AUTO_INCREMENT,
  nomePacote varchar(200) NOT NULL,
  origemPacote varchar(200) NOT NULL,
  destinoPacote varchar(100) NOT NULL,
  atrativosPacote varchar(500) NOT NULL,
  saidaPacote datetime NOT NULL,
  retornoPacote datetime NOT NULL,
  IDusuario int(11) DEFAULT NULL,
  PRIMARY KEY (IDProduto)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
*/

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
